# Generated by Django 4.2.4 on 2024-03-10 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('sending_time', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('manga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BlogApp.manga', verbose_name='Манга')),
            ],
        ),
    ]
