# Generated by Django 4.2.4 on 2024-02-19 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BlogApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo_user/%Y/%m/%d/', verbose_name='Фото пользователя')),
                ('abandoned', models.ManyToManyField(blank=True, related_name='abandoned+', to='BlogApp.manga', verbose_name='Брошено')),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorites+', to='BlogApp.manga', verbose_name='Избранное')),
                ('friends', models.ManyToManyField(blank=True, related_name='friends+', to=settings.AUTH_USER_MODEL, verbose_name='Друзья')),
                ('read', models.ManyToManyField(blank=True, to='BlogApp.manga', verbose_name='Читают')),
                ('read_it', models.ManyToManyField(blank=True, related_name='read_ it+', to='BlogApp.manga', verbose_name='Прочитано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профиль',
                'ordering': ['user'],
            },
        ),
    ]
